language: bash
sudo: required

services:
- docker

before_install:
- docker build --file Dockerfile -t  phlummox/firefox-esr:0.1 .

script:
- docker images | grep phlummox/firefox-esr 

deploy:
  provider: script
  script: bash .travis/push_docker 
  on:
    branch: master

